### ISSUE TITLE
Problems when running pidi-spotify

### ISSUE THREAD

**Issue by Papa-T6** [pimoroni/pidi-plugins#3]
I'm trying to get pidi-spotify up and running but run into the following error whenever I try to run it...

Traceback (most recent call last):
  File "/usr/local/bin/pidi_spotify", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3198, in <module>
    @_call_aside
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3182, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3211, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 590, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 907, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 793, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'fonts' distribution was not found and is required by pidi-display-pil

Any help would be greatly appreciated!

**Comment by Gadgetoid** [comment]
I think this is the result of a fundamentally broken Python environment, I'm not really sure how to recover.

Perhaps running `python3 -m pip install --upgrade fonts` would help.

Sorry for being a year late- it's been a heck of a time, hopefully you've figured this out in the interim!
